version: "3.2"

services:
  papercups:
    container_name: "banking_chatbot_backend"
    image: papercups/papercups:latest
    ports:
      - "3000:3000"
      - "4000:4000"
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && echo 'running' && /entrypoint.sh run"
    depends_on:
      - db
    environment:
      DATABASE_URL: "ecto://postgres:postgres@banking_chatbot_backend_database/postgres"
      # PUT YOUR OWN SECRET KEYBASE HERE (MUST BE AT LEAST 64 BYTES)
      SECRET_KEY_BASE: "afd644dc4c94fcd09b87e8213d49a6b3d26cf29f1ac155dd5e3611f7baeda73a6694ba5d4c2e209b277f1a65dcb0a1d798951b41e3a552ce66e88b8f8e444107"
      BACKEND_URL: "localhost"
      MIX_ENV: "prod"
      REQUIRE_DB_SSL: "false"
      REACT_APP_FILE_UPLOADS_ENABLED: 1
      # Replace with your domain name
      REACT_APP_URL: "app.papercups.io"
  db:
    container_name: "banking_chatbot_backend_database"
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
  chatbot:
    container_name: "banking_chatbot_chatbot"
    user: root
    build: 
      context: ./chatbot
    ports: 
      - "5005:5005"
    depends_on:
      - chatbot_actions
  chatbot_actions:
    container_name: "banking_chatbot_chatbot_actions"
    build: 
      context: ./chatbot/actions
    ports: 
      - "5055:5055"
  lambda:
    container_name: "banking_chatbot_lambda"
    image: lambci/lambda:build-nodejs12.x
    entrypoint: ["/var/rapid/init", "--bootstrap", "/var/runtime/bootstrap", "--enable-msg-logs", "handler.handler"]
    volumes:
      - ./webhook:/var/task:ro,delegated
    ports:
      - 9001:9001
    environment:
      AWS_LAMBDA_FUNCTION_NAME: "webhook"
      DOCKER_LAMBDA_STAY_OPEN: 1
      DOCKER_LAMBDA_WATCH: 1
  frontend:
    container_name: "banking_chatbot_frontend"
    image: node:12-slim
    volumes:
      - ./frontend:/app/
      - nodemodules:/app/node_modules
    working_dir: /app
    command: npm start
    stdin_open: true
    ports:
      - 7000:7000

volumes:
    nodemodules: {}
